import React from "react";

const QuestionBankContext = React.createContext({
    type: "category",
    category: "top",
    name: "Default question",
    question_text: "This is your question text",
    tags: [],
    choices: [],
    feedback: [],
    value: [],
    generalFeedback: "",
    defaultGrade: 1,
    penalty: 0.33,
    isCaseSensitive: false,
    numbering: 0,
    isShuffleAnswers: true,
    isSingleAnswer: true,
    tolerance: [],
    unitGradingType: 0,
    unitPenalty: 0,
    showUnits: 0,
    unitsLeft: 0,
    unitName: [],
    multiplier: [],
    subQuestionText: [],
    subQuestionAnswer: [],
    imageName: "",
    imageData: "",
    dragNo: [],
    dragText: [],
    dragNumOfDrags: [],
    dropNum: [],
    dropShape: [],
    dropCoords: [],
    dropChoice: [],
    issue: "",
    addQuestion: (question) => {},
    removeQuestion: (id) => {},
    editQuestion: (id) => {},
});

export default QuestionBankContext;
