export const defaultQuestion = {
    id: 0,
    type: "category",
    category: "top",
    name: "Default question",
    question_text: "This is your question text",
    tags: [],
    choicesFull: [],
    choices: [],
    feedback: [],
    value: [],
    general_feedback: "",
    default_grade: 1,
    penalty: 0.33,
    case_sensitive: false,
    numbering: 0,
    shuffle_answers: true,
    single_answer: true,
    tolerance: [],
    unitgradingtype: 0,
    unitpenalty: 0,
    showunits: 0,
    unitsleft: 0,
    unitname: [],
    multiplier: [],
    subquestion_text: [],
    subquestion_answer: [],
    image_name: "", //for dragdropmarker-type
    image_data: "",
    drag_no: [],
    drag_text: [],
    drag_noofdrags: [],
    drop_no: [],
    drop_shape: [],
    drop_coords: [],
    drop_choice: [],
    issue: "",
};
